// SHOW_ERROR_TOGGLE_TRUE
export const SHOW_ERROR_TOGGLE_TRUE = 'SHOW_ERROR_TOGGLE_TRUE';
export type SHOW_ERROR_TOGGLE_TRUE = typeof SHOW_ERROR_TOGGLE_TRUE;

// SHOW_ERROR_TOGGLE_FALSE
export const SHOW_ERROR_TOGGLE_FALSE = 'SHOW_ERROR_TOGGLE_FALSE';
export type SHOW_ERROR_TOGGLE_FALSE = typeof SHOW_ERROR_TOGGLE_FALSE;