/****************************** CREATE ******************************/

// CREATE_SUBLEASE_REQUEST
export const CREATE_SUBLEASE_REQUEST = 'CREATE_SUBLEASE_REQUEST';
export type CREATE_SUBLEASE_REQUEST = typeof CREATE_SUBLEASE_REQUEST;

// CREATE_SUBLEASE
export const CREATE_SUBLEASE = 'CREATE_SUBLEASE';
export type CREATE_SUBLEASE = typeof CREATE_SUBLEASE;

// CREATE_SUBLEASE_SUCCESS
export const CREATE_SUBLEASE_SUCCESS = 'CREATE_SUBLEASE_SUCCESS';
export type CREATE_SUBLEASE_SUCCESS = typeof CREATE_SUBLEASE_SUCCESS;

// CREATE_SUBLEASE_FAILURE
export const CREATE_SUBLEASE_FAILURE = 'CREATE_SUBLEASE_FAILURE';
export type CREATE_SUBLEASE_FAILURE = typeof CREATE_SUBLEASE_FAILURE;

/****************************** FETCH ******************************/

// FETCH_SUBLEASES_REQUEST
export const FETCH_SUBLEASES_REQUEST = 'FETCH_SUBLEASES_REQUEST';
export type FETCH_SUBLEASES_REQUEST = typeof FETCH_SUBLEASES_REQUEST;

// FETCH_SUBLEASES
export const FETCH_SUBLEASES = 'FETCH_SUBLEASES';
export type FETCH_SUBLEASES = typeof FETCH_SUBLEASES;

// FETCH_SUBLEASES_SUCCESS
export const FETCH_SUBLEASES_SUCCESS = 'FETCH_SUBLEASES_SUCCESS';
export type FETCH_SUBLEASES_SUCCESS = typeof FETCH_SUBLEASES_SUCCESS;

// FETCH_SUBLEASES_FAILURE
export const FETCH_SUBLEASES_FAILURE = 'FETCH_SUBLEASES_FAILURE';
export type FETCH_SUBLEASES_FAILURE = typeof FETCH_SUBLEASES_FAILURE;

/****************************** UPDATE ******************************/

// UPDATE_SUBLEASE_REQUEST
export const UPDATE_SUBLEASE_REQUEST = 'UPDATE_SUBLEASE_REQUEST';
export type UPDATE_SUBLEASE_REQUEST = typeof UPDATE_SUBLEASE_REQUEST;

// UPDATE_SUBLEASE
export const UPDATE_SUBLEASE = 'UPDATE_SUBLEASE';
export type UPDATE_SUBLEASE = typeof UPDATE_SUBLEASE;

// UPDATE_SUBLEASE_SUCCESS
export const UPDATE_SUBLEASE_SUCCESS = 'UPDATE_SUBLEASE_SUCCESS';
export type UPDATE_SUBLEASE_SUCCESS = typeof UPDATE_SUBLEASE_SUCCESS;

// UPDATE_SUBLEASE_FAILURE
export const UPDATE_SUBLEASE_FAILURE = 'UPDATE_SUBLEASE_FAILURE';
export type UPDATE_SUBLEASE_FAILURE = typeof UPDATE_SUBLEASE_FAILURE;

/****************************** DELETE ******************************/

// DELETE_SUBLEASE_REQUEST
export const DELETE_SUBLEASE_REQUEST = 'DELETE_SUBLEASE_REQUEST';
export type DELETE_SUBLEASE_REQUEST = typeof DELETE_SUBLEASE_REQUEST;

// DELETE_SUBLEASE
export const DELETE_SUBLEASE = 'DELETE_SUBLEASE';
export type DELETE_SUBLEASE = typeof DELETE_SUBLEASE;

// DELETE_SUBLEASE_SUCCESS
export const DELETE_SUBLEASE_SUCCESS = 'DELETE_SUBLEASE_SUCCESS';
export type DELETE_SUBLEASE_SUCCESS = typeof DELETE_SUBLEASE_SUCCESS;

// DELETE_SUBLEASE_FAILURE
export const DELETE_SUBLEASE_FAILURE = 'DELETE_SUBLEASE_FAILURE';
export type DELETE_SUBLEASE_FAILURE = typeof DELETE_SUBLEASE_FAILURE;
